config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :listings do
    resources :messages
    resources :reservations do
      member do
        put 'confirm'
      end
      resources :ratings
    end
  end
  resources :users, only: [:show]
  root "listings#index"
  get 'search', to:'listings#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  
  has_many :messages
  has_many :reservations
  
   enum locations:{
     BPlate: 0,
     Covel: 1, 
     DeNeve: 2, 
     Feast: 3 , 
     BCafe: 4, 
     Rendezvous: 5, 
     LateNight: 6, 
     TheStudy: 7,
     Cafe1919: 8
   }
   
   enum images:{
     0 => "https://i.imgur.com/h54RWvm.jpg",
     1 => "https://i.imgur.com/uQFxGRI.jpg",
     2 => "https://i.imgur.com/0wxAM5k.jpg",
     3 => "https://i.imgur.com/bWwYe93.jpg",
     4 => "https://i.imgur.com/iH56lGH.jpg",
     5 => "https://i.imgur.com/6XF7qW1.jpg",
     6 => "https://i.imgur.com/0wxAM5k.jpg",
     7 => "https://i.imgur.com/3ZfygfP.jpg",
     8 => "https://i.imgur.com/esu8IE0.jpg"
   }
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("time DESC")
    # .paginate(page: params[:page], per_page: 12)
    # uncomment below to enable client-side caching
    # fresh_when(@listings) 
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @messages = @listing.messages.all.order("created_at DESC")
    @message = @listing.messages.new
    
    @reservations = @listing.reservations.all.order("created_at DESC")
    @reservation = @listing.reservations.new
  end

  # GET /listings/new
  def new
    @listing = current_user.listings.build
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.build(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listings_path, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @q = params[:query]
    @listings = Listing.where("title LIKE ? or description LIKE ? or location LIKE ? or price LIKE ?", @q, @q, @q, @q).order("time DESC").paginate(page: params[:page], per_page: 12)
    render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :price, :description, :time, :available_swipes, :location)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
    def cache_key_for_listing_card(listing)
        "listing-#{listing.id}-#{listing.updated_at}"
    end

    def cache_key_for_listing
        "listings-page-#{Listing.maximum(:updated_at)}-#{Message.maximum(:updated_at)}-#{Reservation.maximum(:updated_at)}"
    end
end

app/views/listings/_chat_form.html.erb
<div class="comment-wrapper">
  <div class="panel panel-info">
    <div class="panel-body">
      <hr>      
      <h4><%= @messages.count %> comments</h4>

      <%= form_for [@listing, @message] do |f| %>
        <%= f.text_area :body, class: "form-control textarea", placeholder: "Add a comment..." %>
        <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>
      <% end %>

      <input type="submit" class="btn btn-primary mt-2" value="Submit" form="new_message">
      <ul class="media-list">
        <% @messages.each do |message| %>
          <% if message.body %>
            <% user = User.find(message.user_id) %>
            <li class="media my-2">
              <a href="#" class="pull-left mr-2">
                <%= gravatar_image_tag(user.email, size: 64, alt: current_user.username) %>
              </a>
              
              <div class="media-body">
                <span class="text-muted pull-right">
                  <small class="text-muted"><%= message.message_time %></small>
                </span>
                <strong class="text-success"><%= user.username %></strong>
                <p>
                  <%= message.body %>
                </p>
              </div>
            </li>
          <% end %>
        <% end %>        
      </ul>
    </div>
  </div>
</div>

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :price, :input_html => { :value => '10.00' }%>
    <%= f.input :time %>
    <%= f.input :available_swipes, :input_html => { :value => 1 } %>
    <select name="listing[location]">
      <option value="0">BPlate</option>
      <option value="1">Covel</option>
      <option value="2">DeNeve</option>
      <option value="3">Feast</option>
      <option value="4">BCafe</option>
      <option value="5">Rendezvous</option>
      <option value="6">LateNight</option>
      <option value="7">TheStudy</option>
    </select>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, { class: 'btn btn-primary' }%>
  </div>
<% end %>

app/views/listings/_listing_card.html.erb
<div class="card listing-card mb-3" style="">    
    <img class="card-img-top" src=<%= image_url(Listing.images[listing.location]) %> alt="Card image">
    
    <div class="card-img-overlay">
      <div class="card-overlay-text">
        <span class="listing-card-location"><%= Listing.locations.key(listing.location) %></span>
        <span class="listing-card-price">$<%= number_with_precision(listing.price, :precision => 2) %></span>
      </div>
    </div>
    
    <div class="card-body listing-card-body bg-transparent" style="background-color: rgba(245, 245, 245, 0.4);">
      <div class="listing-card-body-title">
        <img class="listing-card-gravatar-img" src="<%= gravatar_image_url(listing.user.email) %>">
        <%= link_to user_path(listing.user_id) do%>
          <p class="card-title my-2" style="color: white;"><%= listing.user.username %></p>
        <% end %>
        <span class="float-right card-reservations">
          <%= listing.swipes_reserved %>/<%= listing.available_swipes %> Reserved
        </span>
      </div>
    
      <div class="listing-card-description">
        <span><%= listing.description  %></span>
      </div>
    </div>
    
    <div class="card-footer">
      <% if user_signed_in? && current_user.id == listing.user_id %>
        <div style="display: inline-block;">
          <%= link_to edit_listing_path(listing), class:"mr-1" do%>
          <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
          <% end %>
          <%= link_to listing, method: :delete, data: {confirm: "Are you sure you want to delete this listing?"} do%>
          <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
          <% end %>
        </div>
      <% end %>
      <span class="card-status float-right">
        <% status, color = listingStatus(listing, current_user) %>
        <span style="color: <%= color %>"><%= status %></span>
    </div>      
</div>

app/views/listings/_reservation_form.html.erb
<%= simple_form_for [@listing, @reservation] do |f| %>
  <label for="reservation_num_reservations">Reserve Number of Swipes</label>
  <div class="input-group mb-3">
    <%= f.hidden_field :user_id, value: current_user.id %>
    <input type="number" class="form-control" id="reservation_num_reservations" name="reservation[num_reservations]" value="1" aria-label="Recipient's username" aria-describedby="basic-addon2">
    
    <div class="input-group-append">
      <spanid="basic-addon2">
        <% if current_user != @listing.user and @reservations.find{|reservation| reservation.user_id == current_user.id} == nil%>
          <input type="submit" class="btn btn-primary" value="Reserve">
        <% else %>
          <input type="submit" class="btn btn-light" value="Reserve" disabled>
        <% end %>
      </span>
    </div>
  </div>
<% end %>

app/views/listings/_reservation_index.html.erb
<div class="accordion" id="accordionExample">
  <div class="card z-depth-0 bordered">
    <div class="card-header" id="headingMain">
      
      <h4><%= pluralize(@reservations.count, 'Reservation') %></h4>
      <span><%= @listing.swipes_reserved %>/<%= @listing.available_swipes %> Reserved</span>
    </div>
  </div>
  
  <% @reservations.each do |reservation| %>
    <% if reservation.num_reservations %>
      <% user = User.find(reservation.user_id) %>
      <% seller = User.find(@listing.user_id) %>
      
      <div class="card reservation-card z-depth-0 bordered">
        
        <div class="card-header" id="heading<%= reservation.user_id %>">
          <span class="mb-0">
            <button class="btn reservation-gravatar-toggle btn-link" type="button" data-toggle="collapse" data-target="#collapse<%= reservation.user_id %>"
              aria-expanded="true" aria-controls="collapse<%= reservation.user_id %>">
              <img class="reservation-gravatar-img" src="<%= gravatar_image_url(user.email) %>">
              <%= user.username %>
            </button>
          </span>
          <span class="float-right" style="line-height:48px">
            <span>Reserved: <%= reservation.num_reservations %> | </span>
            <span>Seller
              <% if reservation.seller_confirmed %>
                <i class="fa fa-check" style=""></i>
              <% else %>
                <i class="fa fa-times" style=""></i>
              <% end %>|
            </span> 
            <span>Buyer
              <% if reservation.buyer_confirmed %>
                <i class="fa fa-check" style=""></i>
              <% else %>
                <i class="fa fa-times" style=""></i>
              <% end %>
            </span>             
          </span>

        </div>
        
        <div id="collapse<%= reservation.user_id %>" class="collapse <%= current_user.id == user.id ? "show" : "" %>" aria-labelledby="heading<%= reservation.user_id %>"
          data-parent="#accordionExample">
          <div class="card-body reservation-card-body">
            <% @ratings = reservation.ratings.all %>
            <% @rating = reservation.ratings.new %>
            
            <% if current_user.id == reservation.user_id%>
              <% if reservation.seller_confirmed && reservation.buyer_confirmed%>
                <% if @ratings.find_all{ |rating| rating.from_seller == false}.empty? == true %>
                  <%= form_for [@listing, reservation, @rating] do |f| %>
                    <span class="rating-form">
                      <label>Rate your experience: </label>
                    </span>
                    <%= f.hidden_field :comment, value: "hello" %>
                    <%= f.hidden_field :from_seller, value: (current_user.id==user.id)? false : true, type: "hidden" %>
                    <input type="submit" class="btn btn-info mt-2" value="Submit" form="new_rating">
                  <% end %>
                <% end %>
              <% else %>
                <%= button_to(
                      reservation.buyer_confirmed ? "Unconfirm Payment" : "Confirm Payment", 
                      confirm_listing_reservation_path(reservation.listing, reservation),
                      method: :put, 
                      :class => "btn " + (reservation.buyer_confirmed ? "btn-light" : "btn-success")
                    )
                %>
              <% end %>
            <% end %>
            
            <% if current_user.id == @listing.user_id  %>
              <% if reservation.seller_confirmed && reservation.buyer_confirmed%>
                <% if @ratings.find_all{ |rating| rating.from_seller == true}.empty? == true %>
                  <%= form_for [@listing, reservation, @rating] do |f| %>
                    <span class="rating-form">
                      <label>Rate this buyer: </label>
                    </span>
                    <%= f.hidden_field :comment, value: "hello" %>
                    <%= f.hidden_field :from_seller, value: (current_user.id==user.id)? false : true, type: "hidden" %>
                    <input type="submit" class="btn btn-info mt-2" value="Submit" form="new_rating">
                  <% end %>
                <% end %>
              <% else %>
                <%= button_to(
                      reservation.seller_confirmed ? "Unconfirm Payment" : "Confirm Payment", 
                      confirm_listing_reservation_path(reservation.listing, reservation),
                      method: :put, 
                      :class => "btn " + (reservation.seller_confirmed ? "btn-light" : "btn-success")
                    )
                %>
              <% end %>
            <% end %>

            <% @ratings.each do |rating| %>
              <div class="listing-ratings">
                <% if rating.from_seller %>
                  <span>
                    <img class="gravatar-img" src="<%= gravatar_image_url(seller.email) %>">
                    <span>&nbsp;</span><i class="fa fa-arrow-right" style=""></i><span>&nbsp;</span>
                    <img class="gravatar-img" src="<%= gravatar_image_url(user.email) %>">
                  </span>
                <% else %>
                   <span>
                    <img class="gravatar-img" src="<%= gravatar_image_url(user.email) %>">
                     <span>&nbsp;</span><i class="fa fa-arrow-right" style=""></i><span>&nbsp;</span> 
                    <img class="gravatar-img" src="<%= gravatar_image_url(seller.email) %>">
                  </span>
                <% end %>
                 <span>&nbsp;</span><span class="star-rating" data-score=<%= rating.score %>></span>
                </div>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  
</div>

<script>
  $('.rating-form').raty({
    path: '/assets',
    scoreName: 'rating[score]'
  });
  
  $('.star-rating').raty({
    path: '/assets',
    readOnly: true,
  });
</script>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

app/views/listings/index.html.erb
<!-- remove cache and corresponding end tag to disable russian doll caching-->
<% cache(cache_key_for_listing) do %>
  <form class="mb-4" action="/search">
    <input class="form-control" type="text" name="query" placeholder="Search" aria-label="Search">
  </form>
  <div class="card-deck">
    <% @listings.each do |listing| %>
      <%= link_to listing do %>
      <!-- remove cache and corresponding end tag to disable fragment caching-->
        <% cache(cache_key_for_listing_card(listing)) do %>
          <%= render "listing_card", listing: listing %>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

app/views/listings/show.html.erb
<div class="row">
  <div  class="col-lg-7">
    <p>
      <strong>Title:</strong>
      <%= @listing.title %>
    </p>
    
    <p>
      <strong>Location:</strong>
      <%= Listing.locations.key(@listing.location) %>
    </p>
    
    <p>
      <strong>Time:</strong>
      <%= @listing.time %>
    </p>
    
    <p>
      <strong>Price:</strong>
      $<%= number_with_precision(@listing.price, :precision => 2) %>
    </p>
    
    <p>
      <strong>Description:</strong>
      <%= @listing.description %>
    </p>
    
    <p>
      <strong>Posted by</strong>
      <%= link_to @listing.user.username, user_path(@listing.user.id)%>
    </p>
    
    <% if user_signed_in? && current_user.id == @listing.user_id %>
      <%= link_to 'Edit', edit_listing_path(@listing) %> |
    <% end %>
    <%= link_to 'Back', listings_path %>
    
    <% if user_signed_in? %>
      <div>
        <%= render "chat_form" %>
      </div>
    <% end %>
  </div>
  
  <% if user_signed_in? %>
    <div class="col-lg-5">
      <%= render "reservation_form" %>
      <%= render "reservation_index" %>
    </div>
  <% end %>
</div>