config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :listings do
    resources :messages
    resources :reservations do
      member do
        put 'confirm'
      end
      resources :ratings
    end
  end
  resources :users, only: [:show]
  root "listings#index"
  get 'search', to:'listings#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mealman</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="https://tasteofredding.org/wp-content/uploads/2015/05/food-icon.png">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="bg-image"></div>
    
    <% if flash[:notice] %>
      <div class="alert alert-info m-0" role="alert">
        <%= notice %>
      </div>
    <% end %>
    
    <% if flash[:alert] %>
      <div class="alert alert-danger m-0" role="alert">
        <%= alert %>
      </div>
    <% end %>
    
    <nav class="home-nav navbar navbar-expand-lg navbar-dark"> 
    <div class="container">      
      <%= link_to "Mealman", root_path, class: "navbar-brand"%>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link"%>
          </li>
          <% if user_signed_in? %> <!-- check if user is signed in -->
            <li class="nav-item">
              <%= link_to "New Listing", new_listing_path, class: "nav-link"%>
            </li>
          <% end %>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %> <!-- check if user is signed in -->
            <li class="nav-item">
              <%= link_to current_user.username, user_path(current_user), class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"%>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link"%>
            </li>
          <% end %>
        </ul>
      </div>
      </div>
    </nav>
    <div class="background">
      <div class="container pt-3">
        <%= yield %>
      </div>
    </div>
  </body>
</html>